version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - 5000:5000
    networks:
      - backend-nw
      - frontend-nw
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
    networks:
      - frontend-nw
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend

  database:
    container_name: database
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27017:27017
    networks:
      - backend-nw

networks:
  backend-nw:
  frontend-nw:

volumes:
  backend_node_modules:
  frontend_node_modules: